import type { LeadInput } from "../leads/lead.types.js";

const names: Array<
    [
        string,
        string,
        string,
        number | null,
        number | null,
        string,
        string,
        string,
        string[],
    ]
> = [
    [
        "Golden State Air",
        "HVAC",
        "CA",
        84,
        12_000_000,
        "Maya",
        "Patel",
        "Owner",
        ["hiring", "expansion"],
    ],
    [
        "Bay Mechanical Services",
        "HVAC",
        "CA",
        142,
        31_000_000,
        "Daniel",
        "Kim",
        "CEO",
        ["revenue growth"],
    ],
    [
        "Sierra Climate Control",
        "HVAC",
        "CA",
        28,
        4_500_000,
        "Elena",
        "Garcia",
        "Founder",
        ["hiring"],
    ],
    [
        "Pacific Duct Pros",
        "HVAC",
        "CA",
        11,
        950_000,
        "Chris",
        "Moore",
        "Manager",
        [],
    ],
    [
        "North Valley Plumbing",
        "Plumbing",
        "CA",
        65,
        8_700_000,
        "Victor",
        "Chen",
        "President",
        ["expansion"],
    ],
    [
        "Desert Solar Works",
        "Solar",
        "AZ",
        190,
        42_000_000,
        "Ari",
        "Stone",
        "VP Sales",
        ["funding"],
    ],
    [
        "Midwest Restaurant Group",
        "Restaurants",
        "IL",
        220,
        68_000_000,
        "",
        "",
        "",
        [],
    ],
    [
        "Cascade HVAC Partners",
        "HVAC",
        "OR",
        96,
        15_000_000,
        "Nora",
        "Lee",
        "Owner",
        ["hiring"],
    ],
    [
        "LA Comfort Systems",
        "HVAC",
        "CA",
        260,
        74_000_000,
        "Sam",
        "Rivera",
        "CEO",
        ["expansion"],
    ],
    ["Tiny Air Repair", "HVAC", "CA", 4, 320_000, "Pete", "Young", "Owner", []],
    [
        "CalWest Facilities",
        "Facilities",
        "CA",
        120,
        22_000_000,
        "Isha",
        "Rao",
        "Director",
        ["hiring"],
    ],
    [
        "Metro Dental Care",
        "Healthcare",
        "CA",
        48,
        6_200_000,
        "Laura",
        "Hill",
        "Owner",
        [],
    ],
    [
        "Precision Mechanical",
        "Mechanical",
        "CA",
        77,
        10_400_000,
        "Omar",
        "Nasser",
        "Founder",
        ["revenue growth"],
    ],
    ["Summit Retail Supply", "Retail", "NV", 340, 91_000_000, "", "", "", []],
    [
        "Ventura Heating & Air",
        "HVAC",
        "CA",
        39,
        5_900_000,
        "Ana",
        "Torres",
        "Owner",
        ["hiring", "expansion"],
    ],
    [
        "Coastal Refrigeration",
        "HVAC",
        "CA",
        155,
        28_000_000,
        "Ben",
        "Adams",
        "President",
        [],
    ],
    [
        "Keystone IT Services",
        "IT Services",
        "CA",
        88,
        14_500_000,
        "Marie",
        "Cole",
        "CEO",
        ["funding"],
    ],
    [
        "Bakersfield Air Experts",
        "HVAC",
        "CA",
        18,
        1_700_000,
        "",
        "",
        "",
        ["hiring"],
    ],
    [
        "Acme Logistics",
        "Logistics",
        "TX",
        520,
        120_000_000,
        "Rob",
        "Foster",
        "COO",
        ["expansion"],
    ],
    [
        "Orange County Climate",
        "HVAC",
        "CA",
        104,
        18_200_000,
        "Priya",
        "Shah",
        "CEO",
        ["revenue growth"],
    ],
    [
        "Golden State Air LLC",
        "HVAC",
        "CA",
        84,
        12_000_000,
        "Maya",
        "Patel",
        "Owner",
        ["hiring"],
    ],
    [
        "Bay Mechanical Service",
        "HVAC",
        "CA",
        142,
        31_000_000,
        "Daniel",
        "Kim",
        "CEO",
        ["revenue growth", "hiring"],
    ],
    [
        "Valley Electrical",
        "Electrical",
        "CA",
        55,
        7_800_000,
        "Evan",
        "Brooks",
        "Owner",
        ["expansion"],
    ],
    [
        "Monterey Home Comfort",
        "HVAC",
        "CA",
        21,
        2_400_000,
        "Grace",
        "Lin",
        "Founder",
        [],
    ],
    [
        "Fresno Mechanical Group",
        "Mechanical",
        "CA",
        187,
        47_000_000,
        "Hector",
        "Diaz",
        "President",
        ["hiring"],
    ],
    [
        "BluePeak SaaS",
        "SaaS",
        "CA",
        71,
        9_100_000,
        "June",
        "Park",
        "Founder",
        ["funding"],
    ],
    [
        "Sacramento Air Care",
        "HVAC",
        "CA",
        33,
        null,
        "Tom",
        "Baker",
        "Owner",
        ["hiring"],
    ],
    [
        "Riverside HVAC",
        "HVAC",
        "CA",
        null,
        3_100_000,
        "Mina",
        "Singh",
        "Owner",
        [],
    ],
    [
        "NorCal Industrial Cooling",
        "HVAC",
        "CA",
        132,
        36_000_000,
        "Leo",
        "Martin",
        "CEO",
        ["expansion"],
    ],
    [
        "Central Valley Farms",
        "Agriculture",
        "CA",
        150,
        25_000_000,
        "Amy",
        "Woods",
        "Owner",
        [],
    ],
    [
        "South Bay Heat Pump",
        "HVAC",
        "CA",
        44,
        6_900_000,
        "Jose",
        "Cruz",
        "Founder",
        ["revenue growth"],
    ],
    [
        "Western Roofing",
        "Construction",
        "CA",
        95,
        16_000_000,
        "Olivia",
        "King",
        "President",
        ["hiring"],
    ],
    ["Prime Fitness Clubs", "Fitness", "CA", 80, 11_000_000, "", "", "", []],
    [
        "Inland Empire Air",
        "HVAC",
        "CA",
        73,
        13_400_000,
        "Noah",
        "Scott",
        "Owner",
        ["expansion"],
    ],
    [
        "Alameda Controls",
        "Facilities",
        "CA",
        60,
        8_200_000,
        "Lena",
        "Ng",
        "CEO",
        ["hiring"],
    ],
];

export const demoLeads: LeadInput[] = names.map(
    (
        [
            company,
            industry,
            state,
            employees,
            revenue,
            first,
            last,
            title,
            growth,
        ],
        index,
    ) => ({
        company,
        website: `https://${company.toLowerCase().replace(/[^a-z0-9]+/g, "")}.com`,
        domain: `${company.toLowerCase().replace(/[^a-z0-9]+/g, "")}.com`,
        industry,
        productServiceCategory:
            industry === "HVAC"
                ? "Heating, ventilation and air conditioning"
                : industry,
        businessType: ["Restaurants", "Retail", "Fitness"].includes(industry)
            ? "B2C"
            : "B2B",
        employees,
        revenue,
        yearFounded: 1990 + (index % 28),
        bbbRating: index % 5 === 0 ? "A+" : null,
        street: null,
        city: ["Los Angeles", "San Diego", "Sacramento", "Fresno", "Oakland"][
            index % 5
        ],
        state,
        country: "US",
        companyPhone:
            index % 3 === 0
                ? `+14155550${String(index).padStart(2, "0")}`
                : null,
        companyLinkedin:
            index % 4 === 0
                ? `https://linkedin.com/company/${company.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`
                : null,
        ownerFirstName: first || null,
        ownerLastName: last || null,
        ownerTitle: title || null,
        ownerLinkedin: first
            ? `https://linkedin.com/in/${first.toLowerCase()}-${last.toLowerCase()}`
            : null,
        ownerPhone:
            index % 2 === 0 && first
                ? `+14156660${String(index).padStart(2, "0")}`
                : null,
        ownerEmail:
            first && index % 4 !== 3
                ? `${first.toLowerCase()}.${last.toLowerCase()}@${company.toLowerCase().replace(/[^a-z0-9]+/g, "")}.com`
                : null,
        technologies:
            index % 2 === 0
                ? ["ServiceTitan", "QuickBooks"]
                : ["Google Workspace"],
        funding: growth.includes("funding")
            ? "Recent funding noted in imported data"
            : null,
        hiringSignals: growth.includes("hiring")
            ? "Hiring technicians and operations roles"
            : null,
        recentNews: growth.includes("expansion")
            ? "Expanded service territory"
            : null,
        growthSignals: [...growth],
    }),
);
